### ISSUE TITLE
not running after clone

### ISSUE THREAD

**Issue by rohitpatil1997** [mvneerven/pure-pwa#3]
i cloned this repository. but getting this error
" Refused to apply style from 'http://localhost:8766/assets/css/app.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

app.css file not available in this project thats why showing error
![image](https://github.com/mvneerven/pure-pwa/assets/60510071/9eedbdea-4717-4d3a-82e2-d50543fecbd8)

**Comment by mvneerven** [comment]
app.css should be generated by running a process like glenn2223.live-sass (Live SCSS compilation), as described in the readme, but any SCSS to CSS generator, configured to write to /assets/css/app.css, should do.
